basePath: /
schemes:
  - http
paths:
  /subscriptions:
    get:
      summary: Получить список подписок
      description: Возвращает список всех подписок
      tags:
        - subscriptions
      produces:
        - application/json
      responses:
        "200":
          description: OK
          schema:
            type: array
            items:
              $ref: "#/definitions/server.Subscription"
        "204":
          description: No Content
        "400":
          description: Bad Request
          schema:
            $ref: "#/definitions/server.ErrorResponse"
        "404":
          description: Not Found
          schema:
            $ref: "#/definitions/server.ErrorResponse"
        "500":
          description: Internal Server Error
          schema:
            $ref: "#/definitions/server.ErrorResponse"

    post:
      summary: Создать подписку
      description: Создаёт новую подписку
      tags:
        - subscriptions
      consumes:
        - application/json
      produces:
        - application/json
      parameters:
        - name: subscription
          in: body
          description: Подписка
          required: true
          schema:
            $ref: "#/definitions/server.Subscription"
      responses:
        "201":
          description: Created
          schema:
            $ref: "#/definitions/server.ResultResponse"
        "204":
          description: No Content
        "400":
          description: Bad Request
          schema:
            $ref: "#/definitions/server.ErrorResponse"
        "404":
          description: Not Found
          schema:
            $ref: "#/definitions/server.ErrorResponse"
        "405":
          description: Method Not Allowed
          schema:
            $ref: "#/definitions/server.ErrorResponse"
        "500":
          description: Internal Server Error
          schema:
            $ref: "#/definitions/server.ErrorResponse"

  /subscriptions/{id}:
    get:
      summary: Получить информацию о подписке
      description: Возвращает подписку по ID
      tags:
        - subscriptions
      produces:
        - application/json
      parameters:
        - name: id
          in: path
          description: ID подписки
          required: true
          type: integer
          format: int
      responses:
        "200":
          description: OK
          schema:
            $ref: "#/definitions/server.Subscription"
        "400":
          description: Bad Request
          schema:
            $ref: "#/definitions/server.ErrorResponse"
        "404":
          description: Not Found
          schema:
            $ref: "#/definitions/server.ErrorResponse"
        "500":
          description: Internal Server Error
          schema:
            $ref: "#/definitions/server.ErrorResponse"

    put:
      summary: Обновить информацию о подписке
      description: Обновляет подписку по ID
      tags:
        - subscriptions
      consumes:
        - application/json
      produces:
        - application/json
      parameters:
        - name: id
          in: path
          description: ID подписки
          required: true
          type: integer
          format: int
        - name: subscription
          in: body
          description: Обновлённая подписка
          required: true
          schema:
            $ref: "#/definitions/server.Subscription"
      responses:
        "200":
          description: OK
          schema:
            $ref: "#/definitions/server.ResultResponse"
        "400":
          description: Bad Request
          schema:
            $ref: "#/definitions/server.ErrorResponse"
        "404":
          description: Not Found
          schema:
            $ref: "#/definitions/server.ErrorResponse"
        "500":
          description: Internal Server Error
          schema:
            $ref: "#/definitions/server.ErrorResponse"

    delete:
      summary: Удалить подписку
      description: Удаляет подписку по ID
      tags:
        - subscriptions
      produces:
        - application/json
      parameters:
        - name: id
          in: path
          description: ID подписки
          required: true
          type: integer
          format: int
      responses:
        "204":
          description: No Content
        "400":
          description: Bad Request
          schema:
            $ref: "#/definitions/server.ErrorResponse"
        "404":
          description: Not Found
          schema:
            $ref: "#/definitions/server.ErrorResponse"
        "500":
          description: Internal Server Error
          schema:
            $ref: "#/definitions/server.ErrorResponse"

definitions:
  server.ErrorResponse:
    type: object
    properties:
      error:
        type: string
        description: Сообщение об ошибке
    required:
      - error
    example:
      error: Message

  server.ResultResponse:
    type: object
    properties:
      status:
        type: string
        description: Статус ответа
    required:
      - status
    example:
      status: ok

  server.TotalSumResponse:
    type: object
    properties:
      total_sum:
        type: integer
        format: int
        description: Общая сумма
    required:
      - total_sum
    example:
      total_sum: 12345

  server.Subscription:
    type: object
    properties:
      id:
        type: integer
        format: int
        description: ID подписки
        example: 11
      user_id:
        type: string
        format: uuid
        description: Идентификатор пользователя, владеющего подпиской
        example: 550e8400-e29b-41d4-a716-446655440000
      service_name:
        type: string
        description: Название сервиса подписки
        example: Netflix
      price:
        type: integer
        format: int32
        description: Цена подписки в целых единицах
        example: 1499
      start_date:
        type: string
        format: date
        description: Дата начала подписки в формате ISO8601
        example: "2023-07-18"
    required:
      - user_id
      - service_name
      - price
      - start_date
